addpath('lib');
addpath('lib/dwp_scripts');
addpath('lib/bioformats_tools');

%% CHANGE THIS PART %%
% Path and filename for the raw data and csv files. The raw data should be in .nd2 format and the csv file should have the same name as the raw data but with .csv extension. The csv file is generated by running ThunderSTORM on the raw data with a selected roi that covers the 0th order region. The csv file should minimally have the following columns: 'frame', 'x [nm]', 'y [nm]', 'intensity [photon]'. The raw data should be in the format of (x, y, frame) and the pixel size should be in nm. The csv file should have the x and y coordinates in nm as well. The output will be saved in the 'processed_files' folder with the same name as the raw data but with .mat extension. When selecting the 0th order region for running thunderstorm, make sure to take note of the roi coordinates and pixel size, as they will be used in the processing. The roi coordinates should be in the format of [x, y, width, height] in pixel units. The pixel size should be in nm. The spectral calibration file 'speccali.mat' should also be placed in the same folder as the raw data and csv files. The speccali.mat file should contain a variable 'speccali' which has a field 'fy' that is a vector of the y-coordinates of the spectral calibration points in pixel units. The speccali.mat file can be generated by running the spectral calibration script on a calibration sample with known emission wavelengths.

pathdate = '2026-02-05';
pathname = sprintf('/Users/weihong/Desktop/temp/data/%s/',pathdate);

px_size = 110; % nm 
order0_roi = [0, 975, 352, 377]; % x, y, width, height

debug = true;

% use spectral calibration file to determine the pixel range for roi
load(fullfile(pathname, 'speccali.mat'));

wl_min = 535;
wl_max = 800;
wl_guess = 680;
roi_radius = 2;

%% END OF CHANGEABLE PART, DO NOT EDIT BELOW UNLESS YOU KNOW WHAT YOU ARE DOING %%

px_min_roi = floor(dwp_wl2px(wl_min, speccali.fy) / px_size);
px_max_roi = ceil(dwp_wl2px(wl_max, speccali.fy) / px_size);
px_window = abs(px_max_roi - px_min_roi);

roi0.xmin = order0_roi(1) + 1;
roi0.xmax = order0_roi(1) + order0_roi(3);
roi0.ymin = order0_roi(2) + 1;
roi0.ymax = order0_roi(2) + order0_roi(4);

roi1.xmin = roi0.xmin;
roi1.xmax = roi0.xmax;
roi1.ymin = max(order0_roi(2) + min(px_min_roi, px_max_roi), 1);
roi1.ymax = order0_roi(2) + max(px_min_roi, px_max_roi) + order0_roi(4);

% load files for processing
files = struct2table(dir(fullfile(pathname,'*.nd2')));

% removes files that begin with speccali if they exist
if any(startsWith(files{:,'name'},'speccali'))
    files = files(~startsWith(files{:,'name'},'speccali'),:);
end

for ii = 2%:height(files)
    output_filename = sprintf('processed_files/%s/%s.mat', pathdate, files{ii,'name'}{:}(1:end-4));

    % if isfile(output_filename)
    %     fprintf('%s already exists! skipping...\n',output_filename);
    % else
        fprintf('%s does not exist, processing...\n',output_filename);

        % check if the nd2 files and csv files exist
        assert(isfile(fullfile(pathname, files{ii,'name'}{:})), 'File %s does not exist!', fullfile(pathname, files{ii,'name'}{:}));
        assert(isfile(fullfile(pathname, sprintf('%s.csv', files{ii,'name'}{:}(1:end-4)))), 'File %s does not exist!', fullfile(pathname, sprintf('%s.csv', files{ii,'name'}{:}(1:end-4))));

        raw_data = SPLMload(fullfile(pathname, files{ii,'name'}{:}),'nd2','uint16');
        raw_data = permute(raw_data,[2,1,3]);
        raw_data = uint32(raw_data);
        bg_data = uint32(median(raw_data,3));

        csv_data = readtable(fullfile(pathname, sprintf('%s.csv', files{ii,'name'}{:}(1:end-4))),'variableNamingRule','preserve');
        csv_data{:,'x [px]'} = csv_data{:,'x [nm]'} / px_size;
        csv_data{:,'y [px]'} = csv_data{:,'y [nm]'} / px_size;

        img0 = raw_data(roi0.xmin:roi0.xmax, roi0.ymin:roi0.ymax, :);
        img1 = raw_data(roi1.xmin:roi1.xmax, roi1.ymin:roi1.ymax, :);
        bg0 = bg_data(roi0.xmin:roi0.xmax, roi0.ymin:roi0.ymax);
        bg1 = bg_data(roi1.xmin:roi1.xmax, roi1.ymin:roi1.ymax);

        if debug
            % draw the raw data and bg subtracted data for both spatial and spectral regions, with the localizations overlaid
            figure(1); clf;
            tiledlayout(2,2,'TileSpacing','Compact','Padding','Compact');
            selected_locs = (csv_data{:,'frame'} == 1);
            [~, sort_idx] = sort(csv_data{selected_locs,'intensity [photon]'}, 'descend');
            % select the top 10 brightest localizations for visualization
            selected_locs = find(selected_locs);
            selected_locs = selected_locs(sort_idx(1:min(10, sum(selected_locs))));

            nexttile;
            imshow(squeeze(img0(:,:,1))',[]);
            hold on;
            scatter(csv_data{selected_locs,'x [px]'}, csv_data{selected_locs,'y [px]'}, 40, 'r');
            axis image;
            title('Raw data: Spatial Region');

            nexttile;
            imshow(squeeze(img1(:,:,1))',[]);
            hold on;
            scatter(csv_data{selected_locs,'x [px]'}, csv_data{selected_locs,'y [px]'}, 40, 'r');
            scatter(csv_data{selected_locs,'x [px]'}, csv_data{selected_locs,'y [px]'} + px_window, 40, 'g');
            axis image;
            title('Raw data: Spectral Region');

            nexttile;
            imshow(squeeze(img0(:,:,1))' - bg0',[]);
            hold on;
            scatter(csv_data{selected_locs,'x [px]'}, csv_data{selected_locs,'y [px]'}, 40, 'r');
            axis image;
            title('Bg sub: Spatial Region');

            nexttile;
            imshow(squeeze(img1(:,:,1))' - bg1',[]);
            hold on;
            scatter(csv_data{selected_locs,'x [px]'}, csv_data{selected_locs,'y [px]'}, 40, 'r');
            scatter(csv_data{selected_locs,'x [px]'}, csv_data{selected_locs,'y [px]'} + px_window, 40, 'g');
            axis image;
            title('Bg sub: Spectral Region');

            % debug based on the first frame, we visualize the 0th and 1st order regions.

            figure(2); clf;
            tiledlayout(10,5,'TileSpacing','Compact','Padding','Compact');
            for jj = 1:10
                x_idx = round(csv_data{selected_locs(jj),'x [px]'});
                y_idx = round(csv_data{selected_locs(jj),'y [px]'});
                
                nexttile(5*(jj-1)+1);
                imshow(squeeze(img0(...
                    x_idx-roi_radius:x_idx+roi_radius, ...
                    y_idx-roi_radius:y_idx+roi_radius, 1))',[]);
                
                nexttile(5*(jj-1)+2,[1,2]);
                imshow(squeeze(img1(...
                    x_idx-roi_radius:x_idx+roi_radius, ...
                    y_idx-roi_radius:min(size(img1,2), y_idx+roi_radius+px_window), 1)),[]);

                nexttile(5*(jj-1)+4,[1,2]);
                xvalues = 1:px_window+roi_radius*2+1;
                csv_x = csv_data{selected_locs(jj),'x [px]'};
                subpix = csv_x - x_idx; % fractional offset from rounded pixel
                wlvalues = dwp_px2wl((-(xvalues - roi_radius - 1 + subpix) + px_min_roi) * px_size, speccali.fy);
                yvalues = sum(squeeze(img1(...
                    x_idx-roi_radius:x_idx+roi_radius, ...
                    y_idx-roi_radius:min(size(img1,2), y_idx+roi_radius+px_window), 1)),1);
                plot(wlvalues, yvalues);
            end
        end

        % Process all frames and all localizations
        fprintf('Extracting spectra for all %d localizations...\n', height(csv_data));
        
        % Pre-allocate output structure
        output_data = struct();
        output_data.frame = csv_data{:,'frame'};
        output_data.x_px = csv_data{:,'x [px]'};
        output_data.y_px = csv_data{:,'y [px]'};
        output_data.x_nm = csv_data{:,'x [nm]'};
        output_data.y_nm = csv_data{:,'y [nm]'};
        output_data.intensity = csv_data{:,'intensity [photon]'};
        
        % Pre-allocate spectrum arrays
        n_locs = height(csv_data);
        spec_length = px_window + roi_radius*2 + 1;
        output_data.spectrum_raw = zeros(n_locs, spec_length);
        output_data.spectrum_bgsub = zeros(n_locs, spec_length);
        output_data.wavelengths = zeros(n_locs, spec_length);
        
        % Extract spectra for each localization
        for loc_idx = 1:n_locs
            frame = output_data.frame(loc_idx);
            x_csv = output_data.x_px(loc_idx);
            y_csv = output_data.y_px(loc_idx);
            x_idx = round(x_csv);
            y_idx = round(y_csv);
            
            % Check bounds
            if x_idx < roi_radius + 1 || x_idx > size(img1,1) - roi_radius || ...
               y_idx < roi_radius + 1 || y_idx > size(img1,2) - roi_radius - px_window
                fprintf('Localization %d (frame %d) out of bounds, skipping...\n', loc_idx, frame);
                continue;
            end
            
            % Extract spectral line from raw data
            spec_raw = squeeze(img1(x_idx-roi_radius:x_idx+roi_radius, ...
                                    y_idx-roi_radius:y_idx+roi_radius+px_window, frame));
            spectrum_raw = sum(spec_raw, 1);
            
            % Extract spectral line from background-subtracted data
            bg1_sub = double(img1(x_idx-roi_radius:x_idx+roi_radius, ...
                                  y_idx-roi_radius:y_idx+roi_radius+px_window, frame)) - ...
                      double(bg1(x_idx-roi_radius:x_idx+roi_radius, ...
                                 y_idx-roi_radius:y_idx+roi_radius+px_window));
            spectrum_bgsub = sum(bg1_sub, 1);
            
            % Calculate wavelength values
            xvalues = 1:spec_length;
            subpix = x_csv - x_idx; % fractional offset from rounded pixel
            wlvalues = dwp_px2wl((-(xvalues - roi_radius - 1 + subpix) + px_min_roi) * px_size, speccali.fy);
            
            % Store in output
            output_data.spectrum_raw(loc_idx, :) = spectrum_raw;
            output_data.spectrum_bgsub(loc_idx, :) = spectrum_bgsub;
            output_data.wavelengths(loc_idx, :) = wlvalues;
        end
        
        % Save output to mat file
        mkdir(fullfile('processed_files',pathdate));
        save(output_filename, 'output_data');
        fprintf('Saved %s\n', output_filename);
    
end